[package]
name = "dhbw-thesis"
version = "1.0.0"
entrypoint = "lib.typ"
authors = ["Danny Seidel <@DannySeidel>"]
license = "MIT"
description = "Unofficial Template for DHBW"
repository = "https://github.com/DannySeidel/typst-dhbw-template"
keywords = ["dhbw", "thesis"]
categories = ["paper", "thesis", "report"]

[template]
path = "template"
entrypoint = "main.typ"
thumbnail = "thumbnail.png"